ollama_api_endpoint: "http://localhost:11434/api/generate"
ollama_model_name: "llama3.2"
embedding_model_name: "all-MiniLM-L6-v2"
faiss_index_path: "data/embeddings/embeddings_index.faiss"
personal_data_path: "data/personal_data.csv"
top_k: 10
